### ISSUE TITLE
Volume Slider

### ISSUE THREAD

**Issue by kred-jon** [vinceliuice/Qogir-theme#236]
Hello,
For volume slider while hover at top bar is mess up.

Thanks.

**Comment by kred-jon** [comment]
Sure, you can refer to the bottom volume slider, just a short icon without slider as before.

https://user-images.githubusercontent.com/38023611/169177499-1aa45e99-7867-402f-ad15-393725a29659.mp4

**Comment by knimer** [comment]
This applies to Volume slider as well as Brightness slider as well.

Just the icon, the slider is squeezed to the size of the icon so the current level is not showing.

Screen shots below:

![image](https://user-images.githubusercontent.com/32583831/169617089-27ba47a3-04a6-4b20-9c9d-cb858c677bf9.png)

**Comment by knimer** [comment]
Hello,

I upgraded mutter and gnome-shell to 42.2 (both).

Now the slider appears properly - no issue at all.

Screen shots for reference:

![image](https://user-images.githubusercontent.com/32583831/170958279-cbdcf018-bc60-4029-ac18-c7f1f2006259.png)

and

![image](https://user-images.githubusercontent.com/32583831/170958386-0bef17d3-a0a9-4ac0-8229-ee10371fcbed.png)

So, I guess this issue is fixed!!

Can you check @kred-jon ??

**Comment by kred-jon** [comment]
I'm still under Mutter and Gnome-Shell 42.0, so the problem still there.

**Comment by kred-jon** [comment]
Yet problem for Mutter version 42.1 and Gnome-Shell 42.0

**Comment by kred-jon** [comment]
Problem still there, any opinion?

![image](https://user-images.githubusercontent.com/38023611/175442976-01a5f80f-f9b9-45cf-9557-75c00654030e.png)

**Comment by antsif-a** [comment]
Hello. I can reproduce this on Gnome Shell `42.3.1-1`, so problem is definitely in Qogir theme. I hope this gets fixed soon as the bug is quite annoying.

**Comment by kred-jon** [comment]
any help about this ?
